# Generated by Django 2.1.7 on 2021-01-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('description', models.TextField(default='', max_length=2048)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('sort_priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_priority'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('IN_PROCESS', 'Ещё не подтверждён'), ('CONFIRMED', 'Подтверждён'), ('REJECTED', 'Отклонён'), ('FINISHED', 'Завершён')], default='IN_PROCESS', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=2048)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('offer_info', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=2048)),
                ('price', models.CharField(max_length=16)),
                ('image', models.ImageField(upload_to='')),
                ('sort_priority', models.IntegerField()),
                ('service_type', models.CharField(choices=[('_hair', 'Волосы'), ('_nails', 'Ногти')], default='_hair', max_length=128)),
            ],
            options={
                'ordering': ['sort_priority'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
