# Generated by Django 2.1.7 on 2021-01-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
